# 設定方法で困ったら Wiki を見るとよいかもしれません。
# Wiki https://github.com/LAM-SHIP01-JP-PSO2NGS/ngs-log-action/wiki

# このファイルでは # で始まる行はコメント行です。
# コメント行はアプリの動作に関与しませんので、設定の書き方の解説をコメント行で書いてあります。

# これは 1.2.0 以降に追加されたアプリ全体の設定の書き方です。
[global]
# true ならログ先頭に [Action::Show] などのアクションパターンを表示、 false なら非表示
show_action_pattern = false
# 日時の表示形式を設定できます
# 例えば…
#   01:23:45    形式にしたい場合 → "%T"
#   01:23       形式にしたい場合 → "%R"
#   01:23:45 AM 形式にしたい場合 → "%r"
#   01時23分45秒 形式にしたい場合 → "%H時%M分%S秒"
#   ISO8601     形式にしたい場合 → "%+"
#   その他の形式については https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html を参考に記述して下さい。
datetime_format = "%T"
# true ならログ表示に Guild や Party などチャンネル名を表示、 false なら非表示
# なお、 false に設定した場合もチャットの色分けは行われます
# show_channel = false
# ログ表示のカラムの区切り文字列を設定できます。オススメは "\t" または " " です。
column_separator = " "
# ログ表示の名前部分を何文字まで空白文字で桁埋めするか設定します。
# すべて全角で最大文字数のキャラクターネームに合わせるなら 30 を設定します。
# 桁揃えはある程度短い名前までにして、長い名前の人は名前欄がはみ出してもよい場合は少し小さくすると見やすいかもしれません。
name_padding_width = 15
# チャンネル表示を何文字まで空白文字で桁埋めするか設定します。
# 最も長いチャンネル名に合わせる場合は PUBLIC の 6 文字に合わせます。
# channel_padding_width = 0

# show などで表示されるログの色を ANSI256 カラーコードで設定できます。(ver.1.3.0以降)
# カラーコードは https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit を見るとわかりやすいです。
# または https://github.com/junegunn/ansi256#reference-chart も見やすいかもしれません。
# 未指定の場合は以下のコメントアウトで例示するカラーコードが使用されます。
# color_public = 15
# color_party = 14
# color_guild = 172
# color_group = 41
# color_reply = 13
# color_item = 227
# color_system = 8

# 1秒間に何回ログをチェックさせるか設定できます。 (ver.1.3.0以降)
# 1 でも十分に動作しますが、ログのタイミングによってはたまにワンテンポ遅れて反応する気がするかもしれません。
# 5 から 10 くらいに設定すると PSO2NGS のログからさほど遅れずに反応するように感じられると思います。
# 60 など PSO2NGS のフレームレートに近い設定するほど理論上は遅延0に近づきますが、無駄に高い性能要求と負荷になるのでおすすめしません。
# (※PSO2NGSがログをゲーム内で表示してからファイルに書き出すまでにも遅延もあるので、あまり高くしても効果が薄い事もあります。)
# 遅延が気になる場合は 1 から徐々に数値を上げて音反応などで許せる遅延となる設定を探ってください。
# ちなみに 1.23 のように小数点付きで設定もできます。
polling_rate = 5

# ここからは最初の version 1.0.0 からあるログに対するアクションの設定部分です
# きほんてきに NGS Log Action の設定ファイルでは、 [[if]] と書くと1つの「もしｘｘならｙｙする」の
# 設定のはじまりになります。 [[if]] は好きなだけ書いて複数の「もしｘｘならｙｙする」を設定できます。

# 例えば最も簡単な設定例として、
# ↓の設定では『もし【無条件（なんであれ）】でチャットログが流れれば【表示】する』動作をします。

[[if]]
action = {show = true}
# action = {show = true,sound = "C:/Windows/Media/tada.wav"}

# 特に条件を設定する項目を書かなればすべてのチャットログに反応する設定になります。
# やらせたい「何か」は action = に続いて記述します。 show = true は【表示】を行います。

# ほかにも、↓のように action を書くと【表示】＋【音を鳴らす】動作になります。
# action = {show = true, sound = "C:/Windows/Media/notify.wav"}

# また、少しPCに詳しい方なら【コマンド】でお好みアプリを起動したり、制御したりもできます。
# この機能は初心者にはやや難しいですが、事実上動作の可能性は∞です。たぶん。
# action = {command = ["cmd", "/k", "start cmd /k dir"]}

# 無限の可能性と言えば、 get または post アクションで Web API を叩くこともできちゃいます。
# action = {get = "https://example.com/my-get-api/?body={body}&name={name}"}
# get アクション場合は叩く URL に対して流れたチャットログの、本文を{body}、名前を{name}、
# チャンネルを{channel}、日時を{datetime}をそれぞれ代名詞として埋め込めます。

# post アクションの場合は、URLはシンプルな記述のみですが、 HTTP Request Header の
# `ngs-log-action-name`, `ngs-log-action-channel`, `ngs-log-action-datetime` として
# 流れたログの情報をAPIへ伝えられます。会話文本体は HTTP Request Body として投げつけます。
# action = {post = "https://example.com/my-post-api/"}

# action では show + sound + command + post のように複数の動作を組み合わせて実行させられます。

# アクションを行わせたいチャットログを絞り込みたい場合には・・・

# names を設定すると、設定した名前の発言者のチャットログにのみ反応する [[if]] になります。
# 例えば自分のメインキャラ、サブキャラの発言時にのみ発動する [[if]] は次のように書きます
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# channels を設定すると、設定したチャンネルのチャットログにのみ反応する [[if]] になります。
# チャンネルは PUBLIC (=白チャット), PARTY, GUILD（=チーム）, GROUP, REPLY（＝Whisper）から
# 好きな組み合わせで設定します。 例えばパーティーチャットとチームチャットの場合のみ反応する
# [[if]]] にしたければ次のように設定を書きます。
# channels = ["PARTY", "GUILD"]

# keywords を設定すると、設定したキーワードが含まれるログにのみ反応する [[if]] になります。
# keywords = ["メセタ","レアドロ","SG"]

# また、 regex を設定すれば正規表現へのマッチングで反応する [[if]] にもなります。
# 例えば次のように記述すると L,A.M. さんでも LAM さんでも らむ さんでも反応します。
# regex = "(L,?A.?M.?|らむ)"

# [[if]] の発動条件の記述 names, channels, keywords, regex は複数を組み合わせても設定できます。
# 例えば『「チームチャット」で「自キャラ」が「緊急警報」と発言したら・・・』のように。

# version 1.1.0 からは以下の ignore- 系の設定も使えます。
# 名前やキーワード、正規表現で「アクションを行わない条件」も設定できます。
# ignore_names = ["L,A.M."]
# ignore_keywords = ["/la sit"]
# ignore_regex = "^/"

# 以下に実用的かもしれないサンプルをいくつかコメントアウトの状態で書いておきます。
# 自身のお好みにあわせた設定をしてお使いになって下さい。

# 「チームチャット」で「自分」が「緊急警報発令」と書いたら
# その内容を Web API にも伝えてくれる [[if]] の例
# [[if]]
# channels = ["GUILD"]
# names = ["L,A.M."]
# keywords = ["緊急警報発令"]
# action = {post = "https://example.com/api/emergency"}

# 「自分の名前」が呼ばれたら音を鳴らす設定の例
# [[if]]
# action = {sound = "C:/Windows/Media/notify.wav"}
# keywords = ["L,A.M.", "らむさん", "ラムさん"]

# 自分が「チームチャット」「白チャット」「パーティーチャット」のいずれかで
# 「☔雷雨」と書いたら、その内容を Web API にも伝えてくれる [[if]] の例。
# ちなみにPSO2NGSゲーム内では表示されない絵文字もコピペなどで■の形で書ける場合は、
# 書いた通りの絵文字としてデータ上は扱われてる場合もあるようです。
# [[if]]
# action = {post = "https://example.com/api/thunderstrom"}
# channels = ["GUILD", "PUBLIC", "PARTY"]
# keywords = ["☔雷雨"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# 自分が「/la console2」（ロビアク）を発動したら表示する例。
# オートワードと組み合わせるとクエストやトライアルの開始と完了の時刻を確認したりにも使えるかも。
# 同様に老練の討伐時刻をメモする用途などで使ってみてもたぶん便利です。
# [[if]]
# keywords = ["/la console2"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]
# action = {show=true}

# # ここから 1.3.0 で追加したアイテムログ機能の設定例です。
# # ↓この設定ですべてのアイテムの取得をログ表示＆集計します
# [[if]]
# # 対象をアイテム取得系のログに設定します(Itemを設定するとチャットログには反応しなくなります)
# target = "Item"
# # show = true で表示、
# # count = true で集計されます。
# action = {show = true, count = true}
# # keyword, regex, names などで対象アイテムを絞る事もできます
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# # ↓重要かもしれないレアアイテムを入手したら音を鳴らす設定
# [[if]]
# target = "Item"
# action = {sound = "C:/Windows/Media/tada.wav"}
# keywords = ["ストラーガ", "フォーシスカタナ", "ヴィアルトボウ", "ソール", "キーパ", "ギガス", "Ⅲ", "Sign"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# # 指定のアイテムが一定数集計される都度、集計結果を表示しつつ、音を鳴らす設定
# [[if]]
# # item_counts の条件を満たしたら取得アイテム集計を表示しつつ音を鳴らす
# action = { show_item_counts = true, sound = "C:/Windows/Media/tada.wav" }
# # メセタを 1k 取得ごと、
# # エアルノート各種を20個取得ごと、
# # 何かしらのカプセルのⅢを5個取得ごと、アクションさせる設定
# item_counts = [ { keywords = ["Meseta"], every = 1000 },
#                 { keywords = ["C/エアルノート"], every = 20 },
#                 { regex = "C/.*Ⅲ", every = 5 }
#               ]

# # ↓自分が /la sivapose1 ロビアクを使う（ログに流す）と、
# # 集計結果を表示(show_item_counts)し、集計状態をリセット(reset_item_result)します。
# # もちろん、ロビアクではなく ##集計おわり## のようなログをキーワードに設定もできます。
# [[if]]
# action = {show_item_counts = true, reset_item_counts = true}
# keywords = ["/la sivapose1", "#reset"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# # ↓自分が /la ippuku ロビアクを使う（ログに流す）と、集計結果を表示します。
# [[if]]
# action = {show_item_counts = true}
# keywords = ["/la ippuku", "#result"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]
