# このファイルでは # で始まる行はコメント行です。
# コメント行はアプリの動作に関与しませんので、設定の書き方の解説をコメント行で書いてあります。

# きほんてきに NGS Log Action の設定ファイルでは、 [[if]] と書くと1つの「もしｘｘならｙｙする」の
# 設定のはじまりになります。 [[if]] は好きなだけ書いて複数の「もしｘｘならｙｙする」を設定できます。

# 例えば最も簡単な設定例として、
# ↓の設定では『もし【無条件（なんであれ）】でチャットログが流れれば【表示】する』動作をします。

[[if]]
action = {show = true}

# 特に条件を設定する項目を書かなればすべてのチャットログに反応する設定になります。
# やらせたい「何か」は action = に続いて記述します。 show = true は【表示】を行います。

# ほかにも、↓のように action を書くと【表示】＋【音を鳴らす】動作になります。
# action = {show = true, sound = "C:/Windows/Media/notify.wav"}

# また、少しPCに詳しい方なら【コマンド】でお好みアプリを起動したり、制御したりもできます。
# この機能は初心者にはやや難しいですが、事実上動作の可能性は∞です。たぶん。
# action = {command = ["cmd", "/k", "start cmd /k dir"]}

# 無限の可能性と言えば、 get または post アクションで Web API を叩くこともできちゃいます。
# action = {get = "https://example.com/my-get-api/?body={body}&name={name}"}
# get アクション場合は叩く URL に対して流れたチャットログの、本文を{body}、名前を{name}、
# チャンネルを{channel}、日時を{datetime}をそれぞれ代名詞として埋め込めます。

# post アクションの場合は、URLはシンプルな記述のみですが、 HTTP Request Header の
# `ngs-log-action-name`, `ngs-log-action-channel`, `ngs-log-action-datetime` として
# 流れたログの情報をAPIへ伝えられます。会話文本体は HTTP Request Body として投げつけます。
# action = {post = "https://example.com/my-post-api/"}

# action では show + sound + command + post のように複数の動作を組み合わせて実行させられます。

# アクションを行わせたいチャットログを絞り込みたい場合には・・・

# names を設定すると、設定した名前の発言者のチャットログにのみ反応する [[if]] になります。
# 例えば自分のメインキャラ、サブキャラの発言時にのみ発動する [[if]] は次のように書きます
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# channels を設定すると、設定したチャンネルのチャットログにのみ反応する [[if]] になります。
# チャンネルは PUBLIC (=白チャット), PARTY, GUILD（=チーム）, GROUP, REPLY（＝Whisper）から
# 好きな組み合わせで設定します。 例えばパーティーチャットとチームチャットの場合のみ反応する
# [[if]]] にしたければ次のように設定を書きます。
# channels = ["PARTY", "GUILD"]

# keywords を設定すると、設定したキーワードが含まれるログにのみ反応する [[if]] になります。
# keywords = ["メセタ","レアドロ","SG"]

# また、 regex を設定すれば正規表現へのマッチングで反応する [[if]] にもなります。
# 例えば次のように記述すると L,A.M. さんでも LAM さんでも らむ さんでも反応します。
# regex = "(L,?A.?M.?|らむ)"

# [[if]] の発動条件の記述 names, channels, keywords, regex は複数を組み合わせても設定できます。
# 例えば『「チームチャット」で「自キャラ」が「緊急警報」と発言したら・・・』のように。

# 以下に実用的かもしれないサンプルをいくつかコメントアウトの状態で書いておきます。
# 自身のお好みにあわせた設定をしてお使いになって下さい。

# なお、NGS ゲーム内のチャットログでは ■ のようにお豆腐下

# 「チームチャット」で「自分」が「緊急警報発令」と書いたら
# その内容を Web API にも伝えてくれる [[if]] の例
# [[if]]
# channels = ["GUILD"]
# names = ["L,A.M."]
# keywords = ["緊急警報発令"]
# action = {post = "https://example.com/api/emergency"}

# 「自分の名前」が呼ばれたら音を鳴らす設定の例
# [[if]]
# action = {sound = "C:/Windows/Media/notify.wav"}
# keywords = ["L,A.M.", "らむさん", "ラムさん"]

# 自分が「チームチャット」「白チャット」「パーティーチャット」のいずれかで
# 「☔雷雨」と書いたら、その内容を Web API にも伝えてくれる [[if]] の例。
# ちなみにPSO2NGSゲーム内では表示されない絵文字もコピペなどで■の形で書ける場合は、
# 書いた通りの絵文字としてデータ上は扱われてる場合もあるようです。
# [[if]]
# action = {post = "https://example.com/api/thunderstrom"}
# channels = ["GUILD", "PUBLIC", "PARTY"]
# keywords = ["☔雷雨"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]

# 自分が「/la console2」（ロビアク）を発動したら表示する例。
# オートワードと組み合わせるとクエストやトライアルの開始と完了の時刻を確認したりにも使えるかも。
# 同様に老練の討伐時刻をメモする用途などで使ってみてもたぶん便利です。
# [[if]]
# keywords = ["/la console2"]
# names = ["L,A.M.", "L,A.M.Ⅱ", "L,A.M.Ⅲ"]
# action = {show=true}


